feat(*)ADD File README.md
GrupoZapVivaReal/mongo-collector-metrics pull request #2
Opened 2018-06-06 20:23 UTC by jamessantos10

Esse é ReadME referente ao respositório mongo-collector-metrics.

2018-06-06 20:48 UTC, souzabrunoftw requested changes
Few points I think you should consider. Also, congratz on the great doc!!

2018-06-06 20:48 UTC, souzabrunoftw commented on README.md
> +After that, we access the link http://prometheus.private.prod.vivareal.io and run the following query `mongodb_mongod_connections`, then see the result below as evidence that the logs are being sent
The `PROD` URL shouldn't be fixed, gives the impression that `QA` doesn't exist.
Maybe use a placeholder like `http://prometheus.private.<env>.vivareal.io`

2018-06-06 20:48 UTC, souzabrunoftw commented on README.md
> +![captura de tela de 2018-05-17 14-01-31](https://user-images.githubusercontent.com/35613398/40192456-d553e1a4-59da-11e8-83ec-b4e148f895f1.png)
Hide Chrome tabs :smile: and maybe store the image in the directory, in an assets folder

2018-06-06 20:48 UTC, souzabrunoftw commented on README.md
> +![captura de tela de 2018-06-06 15-48-30](https://user-images.githubusercontent.com/35613398/41058803-1d3f875e-69a1-11e8-8ab0-1c94c641c37f.png)
Hide Chrome tabs :smile: and maybe store the image in the directory, in an assets folder

2018-06-06 20:48 UTC, souzabrunoftw commented on README.md
> +## Install
Install should be **How to Deploy**

2018-06-07 18:13 UTC, souzabrunoftw requested changes
Just a few more points I've noticed. Sorry for being annoying ;)

2018-06-07 18:13 UTC, souzabrunoftw commented on README.md
>  this repository was created for the mongodb metrics collector, this app sends metrics to the prometheus
`this` should be uppercase.

2018-06-07 18:13 UTC, souzabrunoftw commented on README.md
> +![image](https://user-images.githubusercontent.com/28811010/41117258-e661e35e-6a62-11e8-9032-1b431a910a90.png)
This screenshot is better, but you could cut the blank part in the bottom.

2018-06-07 18:13 UTC, souzabrunoftw commented on README.md
> +Access Prometheus  QA or Prod interface and execute this command **mongodb_mongod** and select query you prefer.
Too many blank spaces between `Prometheus` and `QA`

2018-06-07 20:08 UTC, souzabrunoftw approved these changes

2018-06-08 17:15 UTC, williamnaltchadjian approved these changes
LGTM

2018-06-08 17:17 UTC, merged